# gnu coreutils
Register-ArgumentCompleter -Native -CommandName arch, b2sum, base32, base64, basename, basenc, cat, chcon, chgrp, chmod, chown, chroot, cksum, comm, cp, csplit, cut, date, dd, df, dircolors, dirname, du, echo, expand, factor, fmt, fold, head, id, install, join, ln, ls, md5sum, mkdir, mkfifo, mknod, mktemp, mv, nice, nl, nproc, numfmt, od, paste, pathchk, pinky, pr, printenv, ptx, readlink, realpath, rm, rmdir, runcon, seq, sha1sum, sha224sum, sha256sum, sha384sum, sha512sum, shred, shuf, sort, split, stat, stdbuf, stty, stty, sum, sync, tac, tail, tee, timeout, touch, tr, truncate, tty, uname, unexpand, uniq, wc, who -ScriptBlock {
  param ([string]$wordToComplete, [System.Management.Automation.Language.CommandAst]$commandAst, [int]$cursorPosition)
  @(if ($wordToComplete.StartsWith('-')) {
      switch -CaseSensitive (Split-Path -LeafBase $commandAst.GetCommandName()) {
        arch { '--help', '--version'; break }
        basename { '-a', '--multiple', '-s', '--suffix=', '-z', '--zero', '--help', '--version'; break }
        basenc { '--base64', '--base64url', '--base32', '--base32hex', '--base16', '--base2msbf', '--base2lsbf', '-d', '--decode', '-i', '--ignore-garbage', '-w', '--wrap=0', '--wrap=76', '--z85', '--help', '--version'; break }
        cat { '-A', '--show-all', '-b', '--number-nonblank', '-e', '-E', '--show-ends', '-n', '--number', '-s', '--squeeze-blank', '-t', '-T', '--show-tabs', '-u', '-v', '--show-nonprinting', '--help', '--version'; break }
        chcon { '--dereference', '-h', '--no-dereference', '-u', '--user=', '-r', '--role=', '-t', '--type=', '-l', '--range=', '--no-preserve-root', '--preserve-root', '--reference=', '-R', '--recursive', '-v', '--verbose', '-H', '-L', '-P', '--help', '--version'; break }
        chgrp { '-c', '--changes', '-f', '--silent', '--quiet', '-v', '--verbose', '--dereference', '-h', '--no-dereference', '--from=', '--no-preserve-root', '--preserve-root', '--reference=', '-R', '--recursive', '-H', '-L', '-P', '--help', '--version'; break }
        chmod { '-c', '--changes', '-f', '--silent', '--quiet', '-v', '--verbose', '--dereference', '-h', '--no-dereference', '--no-preserve-root', '--preserve-root', '--reference=', '-R', '--recursive', '-H', '-L', '-P', '--help', '--version'; break }
        chown { '-c', '--changes', '-f', '--silent', '--quiet', '-v', '--verbose', '--dereference', '-h', '--no-dereference', '--from=', '--no-preserve-root', '--preserve-root', '--reference=', '-R', '--recursive', '-H', '-L', '-P', '--help', '--version'; break }
        chroot { '--groups=', '--userspec=', '--skip-chdir', '--help', '--version'; break }
        cksum { '-a', '--algorithm=sysv', '--algorithm=bsd', '--algorithm=crc', '--algorithm=crc32b', '--algorithm=md5', '--algorithm=sha1', '--algorithm=sha224', '--algorithm=sha256', '--algorithm=sha384', '--algorithm=sha512', '--algorithm=blake2b', '--algorithm=sm3', '--base64', '-c', '--check', '-l', '--length=', '--raw', '--tag', '--untagged', '-z', '--zero', '--ignore-missing', '--quiet', '--status', '--strict', '-w', '--warn', '--debug', '--help', '--version'; break }
        comm { '-1', '-2', '-3', '--check-order', '--nocheck-order', '--output-delimiter=', '--total', '-z', '--zero-terminated', '--help', '--version'; break }
        cp { '-a', '--archive', '--attributes-only', '--backup', '--backup=none', '--backup=off', '--backup=numbered', '--backup=t', '--backup=existing', '--backup=nil', '--backup=simple', '--backup=never', '-b', '--copy-contents', '-d', '--debug', '-f', '--force', '-i', '--interactive', '-H', '-l', '--link', '-L', '--dereference', '-n', '--no-clobber', '-P', '--no-dereference', '-p', '--preserve', '--preserve=mode', '--preserve=ownership', '--preserve=timestamps', '--preserve=links', '--preserve=context', '--preserve=xattr', '--preserve=all', '--no-preserve=mode', '--no-preserve=ownership', '--no-preserve=timestamps', '--no-preserve=links', '--no-preserve=context', '--no-preserve=xattr', '--no-preserve=all', '--parents', '-R', '-r', '--recursive', '--reflink', '--reflink=auto', '--reflink=always', '--reflink=never', '--remove-destination', '--sparse=auto', '--sparse=always', '--sparse=never', '--strip-trailing-slashes', '-s', '--symbolic-link', '-S', '--suffix=~', '-t', '--target-directory=', '-T', '--no-target-directory', '--update', '--update=all', '--update=none', '--update=none-fail', '--update=older', '-u', '-v', '--verbose', '--keep-directory-symlink', '-x', '--one-file-system', '-Z', '--context', '--context=', '--help', '--version'; break }
        csplit { '-b', '--suffix-format=%02d', '-f', '--prefix=xx', '-k', '--keep-files', '--suppress-matched', '-n', '--digits=位数', '-s', '--quiet', '--silent', '-z', '--elide-empty-files', '--help', '--version'; break }
        cut { '-b', '--bytes=', '-c', '--characters=', '-d', '--delimiter=', '-f', '--fields=', '-n', '--complement', '-s', '--only-delimited', '--output-delimiter=', '-z', '--zero-terminated', '--help', '--version'; break }
        date { '-d', '--date=', '--date=now', '--debug', '-f', '--file=', '-I', '--iso-8601', '--iso-8601=date', '--iso-8601=hours', '--iso-8601=minutes', '--iso-8601=seconds', '--iso-8601=ns', '--resolution', '-R', '--rfc-email', '--rfc-3339=date', '--rfc-3339=seconds', '--rfc-3339=ns', '-r', '--reference=', '-s', '--set=', '-u', '--utc', '--universal', '--help'; break }
        df { '-a', '--all', '-B', '--block-size=M', '--direct', '-h', '--human-readable', '-H', '--si', '-i', '--inodes', '-k', '-l', '--local', '--no-sync', '--output', '--output=source', '--output=fstype', '--output=itotal', '--output=iused', '--output=iavail', '--output=ipcent', '--output=size', '--output=used', '--output=avail', '--output=pcent', '--output=file', '--output=target', '-P', '--portability', '--sync', '--total', '-t', '--type=ext4', '--type=btrfs', '--type=efi', '-T', '--print-type', '-x', '--exclude-type=ext4', '--exclude-type=btrfs', '--exclude-type=efi', '-v', '--help', '--version'; break }
        dircolors { '-b', '--sh', '--bourne-shell', '-c', '--csh', '--c-shell', '-p', '--print-database', '--print-ls-colors', '--help', '--version'; break }
        dirname { '-z', '--zero', '--help', '--version'; break }
        du { '-0', '--null', '-a', '--all', '--apparent-size', '-B', '--block-size=M', '-b', '--bytes', '-c', '--total', '-D', '--dereference-args', '-d', '--max-depth=0', '--files0-from=', '--files0-from=-', '-H', '-h', '--human-readable', '--inodes', '-k', '-L', '--dereference', '-l', '--count-links', '-m', '-P', '--no-dereference', '-S', '--separate-dirs', '--si', '-s', '--summarize', '-t', '--threshold=20M', '--time', '--time=atime', '--time=access', '--time=use', '--time=ctime', '--time=status', '--time-style=full-iso', '--time-style=long-iso', '--time-style=iso', '--time-style=+%s', '-X', '--exclude-from=', '--exclude=', '-x', '--one-file-system', '--help', '--version'; break }
        echo { '-n', '-e', '-E', '--help', '--version'; break }
        expand { '-i', '--initial', '-t', '--tabs=8', '-t', '--tabs=', '--help', '--version'; break }
        factor { '-h', '--exponents', '--help', '--version'; break }
        fmt { '-c', '--crown-margin', '-p', '--prefix=#', '-s', '--split-only', '-t', '--tagged-paragraph', '-u', '--uniform-spacing', '-w', '--width=75', '-g', '--goal=70', '--help', '--version'; break }
        fold { '-b', '--bytes', '-c', '--characters', '-s', '--spaces', '-w', '--width=80', '--help', '--version'; break }
        head { '-c', '--bytes=', '-n', '--lines=', '-q', '--quiet', '--silent', '-v', '--verbose', '-z', '--zero-terminated', '--help', '--version'; break }
        id { '-a', '-Z', '--context', '-g', '--group', '-G', '--groups', '-n', '--name', '-r', '--real', '-u', '--user', '-z', '--zero', '--help', '--version'; break }
        install { '--backup', '--backup=none', '--backup=off', '--backup=numbered', '--backup=t', '--backup=existing', '--backup=nil', '--backup=simple', '--backup=never', '-b', '-c', '-C', '--compare', '-d', '--directory', '-D', '--debug', '-g', '--group=', '-m', '--mode=755', '--mode=644', '-o', '--owner=', '-p', '--preserve-timestamps', '-s', '--strip', '--strip-program=', '-S', '--suffix=~', '-t', '--target-directory=', '-T', '--no-target-directory', '-v', '--verbose', '--preserve-context', '-Z', '--context', '--context=', '--help', '--version'; break }
        join { '-a', '-e', '-i', '--ignore-case', '-j', '-o', '-t', '-v', '-1', '-2', '--check-order', '--nocheck-order', '--header', '-z', '--zero-terminated', '--help', '--version'; break }
        ln { '--backup', '--backup=none', '--backup=off', '--backup=numbered', '--backup=t', '--backup=existing', '--backup=nil', '--backup=simple', '--backup=never', '-b', '-d', '-F', '--directory', '-f', '--force', '-i', '--interactive', '-L', '--logical', '-n', '--no-dereference', '-P', '--physical', '-r', '--relative', '-s', '--symbolic', '-S', '--suffix=~', '-t', '--target-directory=', '-T', '--no-target-directory', '-v', '--verbose', '--help', '--version'; break }
        ls { '-a', '--all', '-A', '--almost-all', '--author', '-b', '--escape', '--block-size=M', '-B', '--ignore-backups', '-c', '-C', '--color', '--color=auto', '--color=always', '--color=never', '-d', '--directory', '-D', '--dired', '-f', '-F', '--classify', '--classify=', '--file-type', '--format=across', '--format=commas', '--format=horizontal', '--format=long', '--format=single-column', '--format=verbose', '--format=vertical', '--full-time', '-g', '--group-directories-first', '-G', '--no-group', '-h', '--human-readable', '--si', '-H', '--dereference-command-line', '--dereference-command-line-symlink-to-dir', '--hide=', '--hyperlink', '--hyperlink=auto', '--hyperlink=always', '--hyperlink=never', '--indicator-style=none', '--indicator-style=slash', '--indicator-style=file-type', '--indicator-style=classify', '-i', '--inode', '-I', '--ignore=', '-k', '--kibibytes', '-l', '-L', '--dereference', '-m', '-n', '--numeric-uid-gid', '-N', '--literal', '-o', '-p', '--indicator-style=slash', '-q', '--hide-control-chars', '--show-control-chars', '-Q', '--quote-name', '--quoting-style=literal', '--quoting-style=locale', '--quoting-style=shell', '--quoting-style=shell-always', '--quoting-style=shell-escape', '--quoting-style=shell-escape-always', '--quoting-style=c', '--quoting-style=escape', '-r', '--reverse', '-R', '--recursive', '-s', '--size', '-S', '--sort=none', '--sort=size', '--sort=time', '--sort=version', '--sort=extension', '--sort=name', '--sort=width', '--time=atime', '--time=access', '--time=use', '--time=ctime', '--time=status', '--time=mtime', '--time=modification', '--time=birth', '--time=creation', '--time-style=full-iso', '--time-style=long-iso', '--time-style=iso', '--time-style=locale', '--time-style=+%s', '-t', '-T', '--tabsize=8', '-u', '-U', '-v', '-w', '--width=0', '-x', '-X', '-Z', '--context', '--zero', '-1', '--help', '--version'; break }
        mkdir { '-m', '--mode=755', '--mode=644', '-p', '--parents', '-v', '--verbose', '-Z', '--context', '--context=', '--help', '--version'; break }
        mkfifo { '-m', '--mode=644', '--mode=755', '-Z', '--context', '--context=', '--help', '--version'; break }
        mknod { '-m', '--mode=644', '--mode=755', '-Z', '--context', '--context=', '--help', '--version'; break }
        mktemp { '-d', '--directory', '-u', '--dry-run', '-q', '--quiet', '--suffix=.tmp', '-p', '--tmpdir', '--tmpdir=/tmp/', '-t', '--help', '--version'; break }
        mv { '--backup', '--backup=none', '--backup=off', '--backup=numbered', '--backup=t', '--backup=existing', '--backup=nil', '--backup=simple', '--backup=never', '-b', '--debug', '--exchange', '-f', '--force', '-i', '--interactive', '-n', '--no-clobber', '--no-copy', '--strip-trailing-slashes', '-S', '--suffix=~', '-t', '--target-directory=', '-T', '--no-target-directory', '--update', '--update=all', '--update=none', '--update=none-fail', '--update=older', '-u', '-v', '--verbose', '-Z', '--context', '--help', '--version'; break }
        nice { '-n', '--adjustment=10', '--adjustment=-20', '--adjustment=19', '--help', '--version'; break }
        nl { '-b', '', '--body-numbering=a', '--body-numbering=t', '--body-numbering=n', '--body-numbering=p', '-d', '--section-delimiter====section===', '-f', '', '--footer-numbering=a', '--footer-numbering=t', '--footer-numbering=n', '--footer-numbering=p', '-h', '', '--header-numbering=a', '--header-numbering=t', '--header-numbering=n', '--header-numbering=p', '-i', '--line-increment=1', '-l', '--join-blank-lines=2', '-n', '--number-format=', '--number-format=ln', '--number-format=rn', '--number-format=rz', '-p', '--no-renumber', '-s', '--number-separator=:', '-v', '--starting-line-number=1', '-w', '--number-width=4', '--help', '--version'; break }
        nproc { '--all', '--ignore=8', '--help', '--version'; break }
        numfmt { '--debug', '-d', '--delimiter=:', '--field=1', '--format=%.2f', '--from=none', '--from=auto', '--from=si', '--from=iec', '--from=iec-i', '--from-unit=1', '--grouping', '--header', '--header=1', '--invalid=abort', '--invalid=fail', '--invalid=warn', '--invalid=ignore', '--padding=10', '--round=up', '--round=down', '--round=from-zero', '--round=towards-zero', '--round=nearest', '--suffix=l', '--to=none', '--to=auto', '--to=si', '--to=iec', '--to=iec-i', '--to-unit=1', '-z', '--zero-terminated', '--help', '--version'; break }
        od { '-A', '--address-radix=d', '--address-radix=o', '--address-radix=x', '--address-radix=n', '--endian=big', '--endian=little', '-j', '--skip-bytes=', '-N', '--read-bytes=', '-S', '--strings', '--strings=3', '-t', '--format=a', '--format=c', '--format=d32', '--format=f32', '--format=o32', '--format=u32', '--format=x32', '--format=fB', '--format=fH', '--format=fF', '--format=fD', '--format=fL', '--format=dC', '--format=oC', '--format=uC', '--format=xC', '--format=dS', '--format=oS', '--format=uS', '--format=xS', '--format=dI', '--format=oI', '--format=uI', '--format=xI', '--format=dL', '--format=oL', '--format=uL', '--format=xL', '-v', '--output-duplicates', '-w', '--width', '--width=32', '--traditional', '--help', '--version', '-a', '-b', '-c', '-d', '-f', '-i', '-l', '-o', '-s', '-x'; break }
        paste { '-d', '--delimiters=:', '-s', '--serial', '-z', '--zero-terminated', '--help', '--version'; break }
        pathchk { '-p', '-P', '--portability', '--help', '--version'; break }
        pinky { '-l', '-b', '-h', '-p', '-s', '-f', '-w', '-i', '-q', '--lookup', '--help', '--version'; break }
        pr { '+1:2', '--pages=', '-3', '--columns=3', '-a', '--across', '-c', '--show-control-chars', '-d', '--double-space', '-D', '--date-format=%s', "-e' '8", '--expand-tabs', "--expand-tabs=' '8", '-F', '-f', '--form-feed', '-h', '--header=', "-i' '8", "--output-tabs=' '8", '-J', '--join-lines', '-l', '--length=66', '-m', '--merge', '-n', '--number-lines', "--number-lines=' '5", '-N', '--first-line-number=1', '-o', '--indent=0', '-r', '--no-file-warnings', '-s', '--separator', '--separator=:', '-S', '--sep-string', "--sep-string=' '", '-t', '--omit-header', '-T', '--omit-pagination', '-v', '--show-nonprinting', '-w', '--width=72', '-W', '--page-width=72', '--help', '--version'; break }
        printenv { '-0', '--null', '--help', '--version'; break }
        ptx { '-A', '--auto-reference', '-G', '--traditional', '-F', '--flag-truncation=/', '-M', '--macro-name=xx', '-O', '--format=roff', '-R', '--right-side-refs', '-S', '--sentence-regexp=', '-T', '--format=tex', '-W', '--word-regexp=', '-b', '--break-file=', '-f', '--ignore-case', '-g', '--gap-size=8', '-i', '--ignore-file=', '-o', '--only-file=', '-r', '--references', '-t', '--typeset-mode', '-w', '--width=80', '--help', '--version'; break }
        readlink { '-f', '--canonicalize', '-e', '--canonicalize-existing', '-m', '--canonicalize-missing', '-n', '--no-newline', '-q', '--quiet', '-s', '--silent', '-v', '--verbose', '-z', '--zero', '--help', '--version'; break }
        realpath { '-e', '--canonicalize-existing', '-m', '--canonicalize-missing', '-L', '--logical', '-P', '--physical', '-q', '--quiet', '--relative-to=', '--relative-base=', '-s', '--strip', '--no-symlinks', '-z', '--zero', '--help', '--version'; break }
        rm { '-f', '--force', '-i', '-I', '--interactive', '--interactive=never', '--interactive=once', '--interactive=always', '--one-file-system', '--no-preserve-root', '--preserve-root', '--preserve-root=all', '-r', '-R', '--recursive', '-d', '--dir', '-v', '--verbose', '--help', '--version'; break }
        rmdir { '--ignore-fail-on-non-empty', '-p', '--parents', '-v', '--verbose', '--help', '--version'; break }
        runcon { '-c', '--compute', '-t', '--type=', '-u', '--user=', '-r', '--role=', '-l', '--range=', '--help', '--version'; break }
        seq { '-f', '--format=%.2f', '-s', '--separator=:', '-w', '--equal-width', '--help', '--version'; break }
        shred { '-f', '--force', '-n', '--iterations=3', '--random-source=', '-s', '--size=1G', '-u', '--remove', '--remove=unlink', '--remove=wipe', '--remove=wipesync', '-v', '--verbose', '-x', '--exact', '-z', '--zero', '--help', '--version'; break }
        shuf { '-e', '--echo', '-i', '--input-range=0-99', '-n', '--head-count=100', '-o', '--output=', '--random-source=', '-r', '--repeat', '-z', '--zero-terminated', '--help', '--version'; break }
        sort { '-b', '--ignore-leading-blanks', '-d', '--dictionary-order', '-f', '--ignore-case', '-g', '--general-numeric-sort', '-i', '--ignore-nonprinting', '-M', '--month-sort', '-h', '--human-numeric-sort', '-n', '--numeric-sort', '-R', '--random-sort', '--random-source=', '-r', '--reverse', '--sort=general-numeric', '--sort=human-numeric', '--sort=month', '--sort=numeric', '--sort=random', '--sort=version', '-V', '--version-sort', '--batch-size=1024', '-c', '--check', '--check=diagnose-first', '-C', '--check=quiet', '--check=silent', '--compress-program=gzip', '--debug', '--files0-from=-', '-k', '--key=', '-m', '--merge', '-o', '--output=', '-s', '--stable', '-S', '--buffer-size=512M', '-t', '--field-separator=', '-T', '--temporary-directory=', '--parallel=32', '-u', '--unique', '-z', '--zero-terminated', '--help', '--version'; break }
        split { '-a', '--suffix-length=2', '--additional-suffix=.chk', '-b', '--bytes=', '-C', '--line-bytes=', '-d', '--numeric-suffixes', '--numeric-suffixes=0', '-x', '--hex-suffixes', '--hex-suffixes=', '-e', '--elide-empty-files', '--filter=', '-l', '--lines=', '-n', '--number=', '-t', '--separator=:', '-u', '--unbuffered', '--verbose', '--help', '--version'; break }
        stat { '-L', '--dereference', '-f', '--file-system', '--cached=always', '--cached=default', '--cached=never', '-c  --format=', '--printf=', '-t', '--terse', '--help', '--version'; break }
        stdbuf { '-i', '--input=', '--input=L', '--input=0', '-o', '--output=', '--output=L', '--output=0', '-e', '--error=', '--error=L', '--error=0', '--help', '--version'; break }
        stty { '-a', '--all', '-g', '--save', '-F', '--file=', '--help', '--version', '-clocal', '-cread', '-crtscts', '-cstopb', '-hup', '-hupcl', '-parenb', '-parodd', '-cmspar', '-brkint', '-icrnl', '-ignbrk', '-igncr', '-ignpar', '-imaxbel', '-inlcr', '-inpck', '-istrip', '-iutf8', '-iuclc', '-ixany', '-ixoff', '-ixon', '-parmrk', '-tandem', '-ocrnl', '-ofdel', '-ofill', '-olcuc', '-onlcr', '-onlret', '-onocr', '-opost', '-tabs', '-crtkill', '-crterase', '-ctlecho', '-echo', '-echoctl', '-echoe', '-echok', '-echoke', '-echonl', '-echoprt', '-extproc', '-flusho', '-icanon', '-iexten', '-isig', '-noflsh', '-prterase', '-tostop', '-xcase', '-cbreak', '-cooked', '-decctlq', '-evenp', '-lcase', '-LCASE', '-litout', '-nl', '-oddp', '-parity', '-pass8', '-raw'; break }
        sum { '-r', '-s', '--sysv', '--help', '--version'; break }
        sync { '-d', '--data', '-f', '--file-system', '--help', '--version'; break }
        tac { '-b', '--before', '-r', '--regex', '-s', '--separator=:', '--help', '--version'; break }
        tail { '-c', '--bytes=', '-f', '--follow', '--follow=name', '--follow=descriptor', '-F', '-n', '--lines=', '--max-unchanged-stats=5', '--pid=', '-q', '--quiet', '--silent', '--retry', '-s', '--sleep-interval=1.0', '-v', '--verbose', '-z', '--zero-terminated', '--help', '--version'; break }
        tee { '-a', '--append', '-i', '--ignore-interrupts', '-p', '--output-error', '--output-error=warn', '--output-error=warn-nopipe', '--output-error=exit', '--output-error=exit-nopipe', '--help', '--version'; break }
        timeout { '--foreground', '-k', '--kill-after=1m', '--preserve-status', '-s', '--signal=', '--signal=HUP', '--signal=USR1', '--signal=USR2', '-v', '--verbose', '--help', '--version'; break }
        touch { '-a', '-c', '--no-create', '-d', '--date=', '-f', '-h', '--no-dereference', '-m', '-r', '--reference=', '-t', '--time=access', '--time=atime', '--time=use', '--time=mtime', '--help', '--version'; break }
        tr { '-c', '-C', '--complement', '-d', '--delete', '-s', '--squeeze-repeats', '-t', '--truncate-set1', '--help', '--version'; break }
        truncate { '-c', '--no-create', '-o', '--io-blocks', '-r', '--reference=', '-s', '--size=', '--help', '--version'; break }
        tty { '-s', '--silent', '--quiet', '--help', '--version'; break }
        uname { '-a', '--all', '-s', '--kernel-name', '-n', '--nodename', '-r', '--kernel-release', '-v', '--kernel-version', '-m', '--machine', '-p', '--processor', '-i', '--hardware-platform', '-o', '--operating-system', '--help', '--version'; break }
        unexpand { '-a', '--all', '--first-only', '-t', '--tabs=8', '-t', '--tabs=', '--help', '--version'; break }
        uniq { '-c', '--count', '-d', '--repeated', '-D', '--all-repeated', '--all-repeated=none', '--all-repeated=prepend', '--all-repeated=separate', '-f', '--skip-fields=', '--group', '--group=separate', '--group=prepend', '--group=append', '--group=both', '-i', '--ignore-case', '-s', '--skip-chars=', '-u', '--unique', '-z', '--zero-terminated', '-w', '--check-chars=', '--help', '--version'; break }
        wc { '-c', '--bytes', '-m', '--chars', '-l', '--lines', '--files0-from=', '--files0-from=-', '-L', '--max-line-length', '-w', '--words', '--total=auto', '--total=always', '--total=only', '--total=never', '--help', '--version'; break }
        who { '-a', '--all', '-b', '--boot', '-d', '--dead', '-H', '--heading', '-l，--login', '--lookup', '-m', '-p', '--process', '-q', '--count', '-r', '--runlevel', '-s', '--short', '-t', '--time', '-T', '-w', '--mesg', '-u', '--users', '--message', '--writable', '--help', '--version'; break }
        { @('b2sum', 'md5sum', 'sha1sum', 'sha224sum', 'sha256sum', 'sha384sum', 'sha512sum').Contains($_) } { '-b', '--binary', '-c', '--check', '-l', '--length=', '--tag', '-t', '--text', '-z', '--zero', '--ignore-missing', '--quiet', '--status', '--strict', '-w', '--warn', '--help', '--version'; break }
        { @('base32', 'base64').Contains($_) } { '-d', '--decode', '-i', '--ignore-garbage', '-w', '--wrap=0', '--wrap=76', '--help', '--version'; break }
      }
    }
    else {
      switch -CaseSensitive (Split-Path -LeafBase $commandAst.GetCommandName()) {
        dd { 'bs=512', 'cbs=', 'conv=ascii', 'conv=ebcdic', 'conv=ibm', 'conv=block', 'conv=unblock', 'conv=lcase', 'conv=ucase', 'conv=sparse', 'conv=swab', 'conv=sync', 'conv=excl', 'conv=nocreat', 'conv=notrunc', 'conv=noerror', 'conv=fdatasync', 'conv=fsync', 'count=', 'ibs=512', 'if=', 'iflag=append', 'iflag=direct', 'iflag=directory', 'iflag=dsync', 'iflag=sync', 'iflag=fullblock', 'iflag=nonblock', 'iflag=noatime', 'iflag=nocache', 'iflag=noctty', 'iflag=nofollow', 'obs=512', 'of=', 'oflag=append', 'oflag=direct', 'oflag=directory', 'oflag=dsync', 'oflag=sync', 'oflag=fullblock', 'oflag=nonblock', 'oflag=noatime', 'oflag=nocache', 'oflag=noctty', 'oflag=nofollow', 'seek=', 'skip=', 'status=none', 'status=noxfer', 'status=progress'; break }
        stty { 'cols', 'columns', 'ispeed', 'line', 'min', 'ospeed', 'rows', 'size', 'speed', 'time', 'cs0', 'clocal', 'cread', 'crtscts', 'cstopb', 'hup', 'hupcl', 'parenb', 'parodd', 'cmspar', 'brkint', 'icrnl', 'ignbrk', 'igncr', 'ignpar', 'imaxbel', 'inlcr', 'inpck', 'istrip', 'iutf8', 'iuclc', 'ixany', 'ixoff', 'ixon', 'parmrk', 'tandem', 'bs0', 'cr0', 'ff0', 'nl0', 'ocrnl', 'ofdel', 'ofill', 'olcuc', 'onlcr', 'onlret', 'onocr', 'opost', 'tab0', 'tabs', 'vt0', 'crtkill', 'crterase', 'ctlecho', 'echo', 'echoctl', 'echoe', 'echok', 'echoke', 'echonl', 'echoprt', 'extproc', 'flusho', 'icanon', 'iexten', 'isig', 'noflsh', 'prterase', 'tostop', 'xcase', 'cbreak', 'cooked', 'crt', 'dec', 'decctlq', 'ek', 'evenp', 'lcase', 'LCASE', 'litout', 'nl', 'oddp', 'parity', 'pass8', 'raw', 'sane'; break }
      }
    }).Where{ $_ -like "$wordToComplete*" }
}
