Register-ArgumentCompleter -Native -CommandName editbin -ScriptBlock {
  param ([string]$wordToComplete, [System.Management.Automation.Language.CommandAst]$commandAst, [int]$cursorPosition)
  @(if ($wordToComplete.StartsWith('/')) {
      '/ALLOWBIND', '/ALLOWBIND:NO', '/ALLOWISOLATION', '/ALLOWISOLATION:NO', '/APPCONTAINER', '/APPCONTAINER:NO', '/BIND', '/DYNAMICBASE', '/DYNAMICBASE:NO', '/ERRORREPORT:NONE', '/ERRORREPORT:PROMPT', '/ERRORREPORT:QUEUE', '/ERRORREPORT:SEND', '/GUARD:CF', '/GUARD:NO', '/HEAP:reserve', '/HEAP:commit', '/HIGHENTROPYVA', '/HIGHENTROPYVA:NO', '/INTEGRITYCHECK', '/INTEGRITYCHECK:NO', '/LARGEADDRESSAWARE', '/LARGEADDRESSAWARE:NO', '/NOLOGO', '/NXCOMPAT', '/NXCOMPAT:NO', '/REBASE', '/REBASE:', '/RELEASE', '/SECTION:', '/STACK:', '/SUBSYSTEM:BOOT_APPLICATION', '/SUBSYSTEM:CONSOLE', '/SUBSYSTEM:EFI_APPLICATION', '/SUBSYSTEM:EFI_BOOT_SERVICE_DRIVER', '/SUBSYSTEM:EFI_ROM', '/SUBSYSTEM:EFI_RUNTIME_DRIVER', '/SUBSYSTEM:NATIVE', '/SUBSYSTEM:POSIX', '/SUBSYSTEM:WINDOWS', '/SUBSYSTEM:WINDOWSCE', '/SWAPRUN:', '/TSAWARE', '/TSAWARE:NO', '/VERSION:'
    }).Where{ $_ -like "$wordToComplete*" }
}
