using namespace System.Management.Automation
using namespace System.Management.Automation.Language

Register-ArgumentCompleter -Native -CommandName bzless, less, xzless, zless, zstdless -ScriptBlock {
  param ([string]$wordToComplete)
  @(
    [CompletionResult]::new('-?', '?', [CompletionResultType]::ParameterValue, 'Display help (from command line).')
    [CompletionResult]::new('--help', 'help', [CompletionResultType]::ParameterValue, 'Display help (from command line).')
    [CompletionResult]::new('-a', 'a', [CompletionResultType]::ParameterValue, 'Search skips current screen.')
    [CompletionResult]::new('--search-skip-screen', 'search-skip-screen', [CompletionResultType]::ParameterValue, 'Search skips current screen.')
    [CompletionResult]::new('-A', 'A', [CompletionResultType]::ParameterValue, 'Search starts just after target line.')
    [CompletionResult]::new('--SEARCH-SKIP-SCREEN', 'SEARCH-SKIP-SCREEN', [CompletionResultType]::ParameterValue, 'Search starts just after target line.')
    [CompletionResult]::new('-b', 'b', [CompletionResultType]::ParameterValue, 'Number of buffers.')
    [CompletionResult]::new('--buffers', 'buffers', [CompletionResultType]::ParameterValue, 'Number of buffers.')
    [CompletionResult]::new('-B', 'B', [CompletionResultType]::ParameterValue, "Don't automatically allocate buffers for pipes.")
    [CompletionResult]::new('--auto-buffers', 'auto-buffers', [CompletionResultType]::ParameterValue, "Don't automatically allocate buffers for pipes.")
    [CompletionResult]::new('-c', 'c', [CompletionResultType]::ParameterValue, 'Repaint by clearing rather than scrolling.')
    [CompletionResult]::new('--clear-screen', 'clear-screen', [CompletionResultType]::ParameterValue, 'Repaint by clearing rather than scrolling.')
    [CompletionResult]::new('-d', 'd', [CompletionResultType]::ParameterValue, 'Dumb terminal.')
    [CompletionResult]::new('--dumb', 'dumb', [CompletionResultType]::ParameterValue, 'Dumb terminal.')
    [CompletionResult]::new('-D', 'D', [CompletionResultType]::ParameterValue, 'Set screen colors.')
    [CompletionResult]::new('--color', 'color', [CompletionResultType]::ParameterValue, 'Set screen colors.')
    [CompletionResult]::new('-e', 'e', [CompletionResultType]::ParameterValue, 'Quit at end of file.')
    [CompletionResult]::new('--quit-at-eof', 'quit-at-eof', [CompletionResultType]::ParameterValue, 'Quit at end of file.')
    [CompletionResult]::new('--QUIT-AT-EOF', 'QUIT-AT-EOF', [CompletionResultType]::ParameterValue, 'Quit at end of file.')
    [CompletionResult]::new('-f', 'f', [CompletionResultType]::ParameterValue, 'Force open non-regular files.')
    [CompletionResult]::new('--force', 'force', [CompletionResultType]::ParameterValue, 'Force open non-regular files.')
    [CompletionResult]::new('-F', 'F', [CompletionResultType]::ParameterValue, 'Quit if entire file fits on first screen.')
    [CompletionResult]::new('--quit-if-one-screen', 'quit-if-one-screen', [CompletionResultType]::ParameterValue, 'Quit if entire file fits on first screen.')
    [CompletionResult]::new('-g', 'g', [CompletionResultType]::ParameterValue, 'Highlight only last match for searches.')
    [CompletionResult]::new('--hilite-search', 'hilite-search', [CompletionResultType]::ParameterValue, 'Highlight only last match for searches.')
    [CompletionResult]::new('-G', 'G', [CompletionResultType]::ParameterValue, "Don't highlight any matches for searches.")
    [CompletionResult]::new('--HILITE-SEARCH', 'HILITE-SEARCH', [CompletionResultType]::ParameterValue, "Don't highlight any matches for searches.")
    [CompletionResult]::new('-h', 'h', [CompletionResultType]::ParameterValue, 'Backward scroll limit.')
    [CompletionResult]::new('--max-back-scroll', 'max-back-scroll', [CompletionResultType]::ParameterValue, 'Backward scroll limit.')
    [CompletionResult]::new('-i', 'i', [CompletionResultType]::ParameterValue, 'Ignore case in searches that do not contain uppercase.')
    [CompletionResult]::new('--ignore-case', 'ignore-case', [CompletionResultType]::ParameterValue, 'Ignore case in searches that do not contain uppercase.')
    [CompletionResult]::new('-I', 'I', [CompletionResultType]::ParameterValue, 'Ignore case in all searches.')
    [CompletionResult]::new('--IGNORE-CASE', 'IGNORE-CASE', [CompletionResultType]::ParameterValue, 'Ignore case in all searches.')
    [CompletionResult]::new('-j', 'j', [CompletionResultType]::ParameterValue, 'Screen position of target lines.')
    [CompletionResult]::new('--jump-target', 'jump-target', [CompletionResultType]::ParameterValue, 'Screen position of target lines.')
    [CompletionResult]::new('-J', 'J', [CompletionResultType]::ParameterValue, 'Display a status column at left edge of screen.')
    [CompletionResult]::new('--status-column', 'status-column', [CompletionResultType]::ParameterValue, 'Display a status column at left edge of screen.')
    [CompletionResult]::new('-k', 'k', [CompletionResultType]::ParameterValue, 'Use a compiled lesskey file.')
    [CompletionResult]::new('--lesskey-file', 'lesskey-file', [CompletionResultType]::ParameterValue, 'Use a compiled lesskey file.')
    [CompletionResult]::new('-K', 'K', [CompletionResultType]::ParameterValue, 'Exit less in response to ctrl-C.')
    [CompletionResult]::new('--quit-on-intr', 'quit-on-intr', [CompletionResultType]::ParameterValue, 'Exit less in response to ctrl-C.')
    [CompletionResult]::new('-L', 'L', [CompletionResultType]::ParameterValue, 'Ignore the LESSOPEN environment variable.')
    [CompletionResult]::new('--no-lessopen', 'no-lessopen', [CompletionResultType]::ParameterValue, 'Ignore the LESSOPEN environment variable.')
    [CompletionResult]::new('-m', 'm', [CompletionResultType]::ParameterValue, 'Set prompt style.')
    [CompletionResult]::new('--long-prompt', 'long-prompt', [CompletionResultType]::ParameterValue, 'Set prompt style.')
    [CompletionResult]::new('--LONG-PROMPT', 'LONG-PROMPT', [CompletionResultType]::ParameterValue, 'Set prompt style.')
    [CompletionResult]::new('-n', 'n', [CompletionResultType]::ParameterValue, 'Suppress line numbers in prompts and messages.')
    [CompletionResult]::new('--line-numbers', 'line-numbers', [CompletionResultType]::ParameterValue, 'Suppress line numbers in prompts and messages.')
    [CompletionResult]::new('-N', 'N', [CompletionResultType]::ParameterValue, 'Display line number at start of each line.')
    [CompletionResult]::new('--LINE-NUMBERS', 'LINE-NUMBERS', [CompletionResultType]::ParameterValue, 'Display line number at start of each line.')
    [CompletionResult]::new('-o', 'o', [CompletionResultType]::ParameterValue, 'Copy to log file (standard input only).')
    [CompletionResult]::new('--log-file', 'log-file', [CompletionResultType]::ParameterValue, 'Copy to log file (standard input only).')
    [CompletionResult]::new('-O', 'O', [CompletionResultType]::ParameterValue, 'Copy to log file (unconditionally overwrite).')
    [CompletionResult]::new('--LOG-FILE', 'LOG-FILE', [CompletionResultType]::ParameterValue, 'Copy to log file (unconditionally overwrite).')
    [CompletionResult]::new('-p', 'p', [CompletionResultType]::ParameterValue, 'Start at pattern (from command line).')
    [CompletionResult]::new('--pattern', 'pattern', [CompletionResultType]::ParameterValue, 'Start at pattern (from command line).')
    [CompletionResult]::new('-P', 'P', [CompletionResultType]::ParameterValue, 'Define new prompt.')
    [CompletionResult]::new('--prompt', 'prompt', [CompletionResultType]::ParameterValue, 'Define new prompt.')
    [CompletionResult]::new('-q', 'q', [CompletionResultType]::ParameterValue, 'Quiet the terminal bell.')
    [CompletionResult]::new('--quiet', 'quiet', [CompletionResultType]::ParameterValue, 'Quiet the terminal bell.')
    [CompletionResult]::new('--QUIET', 'QUIET', [CompletionResultType]::ParameterValue, 'Quiet the terminal bell.')
    [CompletionResult]::new('--silent', 'silent', [CompletionResultType]::ParameterValue, 'Quiet the terminal bell.')
    [CompletionResult]::new('--SILENT', 'SILENT', [CompletionResultType]::ParameterValue, 'Quiet the terminal bell.')
    [CompletionResult]::new('-r', 'r', [CompletionResultType]::ParameterValue, 'Output "raw" control characters.')
    [CompletionResult]::new('--raw-control-chars', 'raw-control-chars', [CompletionResultType]::ParameterValue, 'Output "raw" control characters.')
    [CompletionResult]::new('--RAW-CONTROL-CHARS', 'RAW-CONTROL-CHARS', [CompletionResultType]::ParameterValue, 'Output "raw" control characters.')
    [CompletionResult]::new('-s', 's', [CompletionResultType]::ParameterValue, 'Squeeze multiple blank lines.')
    [CompletionResult]::new('--squeeze-blank-lines', 'squeeze-blank-lines', [CompletionResultType]::ParameterValue, 'Squeeze multiple blank lines.')
    [CompletionResult]::new('-S', 'S', [CompletionResultType]::ParameterValue, 'Chop (truncate) long lines rather than wrapping.')
    [CompletionResult]::new('--chop-long-lines', 'chop-long-lines', [CompletionResultType]::ParameterValue, 'Chop (truncate) long lines rather than wrapping.')
    [CompletionResult]::new('-t', 't', [CompletionResultType]::ParameterValue, 'Find a tag.')
    [CompletionResult]::new('--tag', 'tag', [CompletionResultType]::ParameterValue, 'Find a tag.')
    [CompletionResult]::new('-T', 'T', [CompletionResultType]::ParameterValue, 'Use an alternate tags file.')
    [CompletionResult]::new('--tag-file', 'tag-file', [CompletionResultType]::ParameterValue, 'Use an alternate tags file.')
    [CompletionResult]::new('-u', 'u', [CompletionResultType]::ParameterValue, 'Change handling of backspaces, tabs and carriage returns.')
    [CompletionResult]::new('--underline-special', 'underline-special', [CompletionResultType]::ParameterValue, 'Change handling of backspaces, tabs and carriage returns.')
    [CompletionResult]::new('--UNDERLINE-SPECIAL', 'UNDERLINE-SPECIAL', [CompletionResultType]::ParameterValue, 'Change handling of backspaces, tabs and carriage returns.')
    [CompletionResult]::new('-V', 'V', [CompletionResultType]::ParameterValue, 'Display the version number of "less".')
    [CompletionResult]::new('--version', 'version', [CompletionResultType]::ParameterValue, 'Display the version number of "less".')
    [CompletionResult]::new('-w', 'w', [CompletionResultType]::ParameterValue, 'Highlight first new line after forward-screen.')
    [CompletionResult]::new('--hilite-unread', 'hilite-unread', [CompletionResultType]::ParameterValue, 'Highlight first new line after forward-screen.')
    [CompletionResult]::new('-W', 'W', [CompletionResultType]::ParameterValue, 'Highlight first new line after any forward movement.')
    [CompletionResult]::new('--HILITE-UNREAD', 'HILITE-UNREAD', [CompletionResultType]::ParameterValue, 'Highlight first new line after any forward movement.')
    [CompletionResult]::new('-x', 'x', [CompletionResultType]::ParameterValue, 'Set tab stops.')
    [CompletionResult]::new('--tabs', 'tabs', [CompletionResultType]::ParameterValue, 'Set tab stops.')
    [CompletionResult]::new('-X', 'X', [CompletionResultType]::ParameterValue, "Don't use termcap init/deinit strings.")
    [CompletionResult]::new('--no-init', 'no-init', [CompletionResultType]::ParameterValue, "Don't use termcap init/deinit strings.")
    [CompletionResult]::new('-y', 'y', [CompletionResultType]::ParameterValue, 'Forward scroll limit.')
    [CompletionResult]::new('--max-forw-scroll', 'max-forw-scroll', [CompletionResultType]::ParameterValue, 'Forward scroll limit.')
    [CompletionResult]::new('-z', 'z', [CompletionResultType]::ParameterValue, 'Set size of window.')
    [CompletionResult]::new('--window', 'window', [CompletionResultType]::ParameterValue, 'Set size of window.')
    [CompletionResult]::new('-"', '"', [CompletionResultType]::ParameterValue, 'Set shell quote characters.')
    [CompletionResult]::new('--quotes', 'quotes', [CompletionResultType]::ParameterValue, 'Set shell quote characters.')
    [CompletionResult]::new('-~', '~', [CompletionResultType]::ParameterValue, "Don't display tildes after end of file.")
    [CompletionResult]::new('--tilde', 'tilde', [CompletionResultType]::ParameterValue, "Don't display tildes after end of file.")
    [CompletionResult]::new('-#', '#', [CompletionResultType]::ParameterValue, 'Set horizon')
    [CompletionResult]::new('--shift', 'shift', [CompletionResultType]::ParameterValue, 'Set horizon')
    [CompletionResult]::new('--exit-follow-on-close', 'exit-follow-on-close', [CompletionResultType]::ParameterValue, 'Exit F command on a pipe when writer closes pipe.')
    [CompletionResult]::new('--file-size', 'file-size', [CompletionResultType]::ParameterValue, 'Automatically determine the size of the input file.')
    [CompletionResult]::new('--follow-name', 'follow-name', [CompletionResultType]::ParameterValue, 'The F command changes files if the input file is renamed.')
    [CompletionResult]::new('--header', 'header', [CompletionResultType]::ParameterValue, 'Use L lines (starting at line N) and C columns as headers.')
    [CompletionResult]::new('--incsearch', 'incsearch', [CompletionResultType]::ParameterValue, 'Search file as each pattern character is typed in.')
    [CompletionResult]::new('--intr', 'intr', [CompletionResultType]::ParameterValue, 'Use C instead of ^X to interrupt a read.')
    [CompletionResult]::new('--lesskey-context', 'lesskey-context', [CompletionResultType]::ParameterValue, 'Use lesskey source file contents.')
    [CompletionResult]::new('--lesskey-src', 'lesskey-src', [CompletionResultType]::ParameterValue, 'Use a lesskey source file.')
    [CompletionResult]::new('--line-num-width', 'line-num-width', [CompletionResultType]::ParameterValue, 'Set the width of the -N line number field to N characters.')
    [CompletionResult]::new('--match-shift', 'match-shift', [CompletionResultType]::ParameterValue, 'Show at least N characters to the left of a search match.')
    [CompletionResult]::new('--modelines', 'modelines', [CompletionResultType]::ParameterValue, 'Read N lines from the input file and look for vim modelines.')
    [CompletionResult]::new('--mouse', 'mouse', [CompletionResultType]::ParameterValue, 'Enable mouse input.')
    [CompletionResult]::new('--no-keypad', 'no-keypad', [CompletionResultType]::ParameterValue, "Don't send termcap keypad init/deinit strings.")
    [CompletionResult]::new('--no-histdups', 'no-histdups', [CompletionResultType]::ParameterValue, 'Remove duplicates from command history.')
    [CompletionResult]::new('--no-number-headers', 'no-number-headers', [CompletionResultType]::ParameterValue, "Don't give line numbers to header lines.")
    [CompletionResult]::new('--no-search-header-lines', 'no-search-header-lines', [CompletionResultType]::ParameterValue, 'Searches do not include header lines.')
    [CompletionResult]::new('--no-search-header-columns', 'no-search-header-columns', [CompletionResultType]::ParameterValue, 'Searches do not include header columns.')
    [CompletionResult]::new('--no-search-headers', 'no-search-headers', [CompletionResultType]::ParameterValue, 'Searches do not include header lines or columns.')
    [CompletionResult]::new('--no-vbell', 'no-vbell', [CompletionResultType]::ParameterValue, "Disable the terminal's visual bell.")
    [CompletionResult]::new('--redraw-on-quit', 'redraw-on-quit', [CompletionResultType]::ParameterValue, 'Redraw final screen when quitting.')
    [CompletionResult]::new('--rscroll', 'rscroll', [CompletionResultType]::ParameterValue, 'Set the character used to mark truncated lines.')
    [CompletionResult]::new('--save-marks', 'save-marks', [CompletionResultType]::ParameterValue, 'Retain marks across invocations of less.')
    [CompletionResult]::new('--search-options', 'search-options', [CompletionResultType]::ParameterValue, 'Set default options for every search.')
    [CompletionResult]::new('--show-preproc-errors', 'show-preproc-errors', [CompletionResultType]::ParameterValue, 'Display a message if preprocessor exits with an error status.')
    [CompletionResult]::new('--proc-backspace', 'proc-backspace', [CompletionResultType]::ParameterValue, 'Process backspaces for bold/underline.')
    [CompletionResult]::new('--PROC-BACKSPACE', 'PROC-BACKSPACE', [CompletionResultType]::ParameterValue, 'Treat backspaces as control characters.')
    [CompletionResult]::new('--proc-return', 'proc-return', [CompletionResultType]::ParameterValue, 'Delete carriage returns before newline.')
    [CompletionResult]::new('--PROC-RETURN', 'PROC-RETURN', [CompletionResultType]::ParameterValue, 'Treat carriage returns as control characters.')
    [CompletionResult]::new('--proc-tab', 'proc-tab', [CompletionResultType]::ParameterValue, 'Expand tabs to spaces.')
    [CompletionResult]::new('--PROC-TAB', 'PROC-TAB', [CompletionResultType]::ParameterValue, 'Treat tabs as control characters.')
    [CompletionResult]::new('--status-col-width', 'status-col-width', [CompletionResultType]::ParameterValue, 'Set the width of the -J status column to N characters.')
    [CompletionResult]::new('--status-line', 'status-line', [CompletionResultType]::ParameterValue, 'Highlight or color the entire line containing a mark.')
    [CompletionResult]::new('--use-backslash', 'use-backslash', [CompletionResultType]::ParameterValue, 'Subsequent options use backslash as escape char.')
    [CompletionResult]::new('--use-color', 'use-color', [CompletionResultType]::ParameterValue, 'Enables colored text.')
    [CompletionResult]::new('--wheel-lines', 'wheel-lines', [CompletionResultType]::ParameterValue, 'Each click of the mouse wheel moves N lines.')
    [CompletionResult]::new('--wordwrap', 'wordwrap', [CompletionResultType]::ParameterValue, 'Wrap lines at spaces.')
  ) | Where-Object CompletionText -Like "$wordToComplete*"
}
