click_interval 0.14
cursor_blink_interval 0
cursor_shape beam
enable_audio_bell no
hide_window_decorations yes
initial_window_height 35c
initial_window_width 120c
map alt++ new_os_window bash
map alt+enter toggle_fullscreen
map f11 toggle_fullscreen
mouse_map right click grabbed,ungrabbed paste_from_clipboard
remember_window_size no
shell pwsh
show_hyperlink_targets yes
sync_to_monitor no
visual_bell_color #666
visual_bell_duration 0.22 linear
